<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Covoiturage extends \App\Entity\Covoiturage implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avis' => [parent::class, 'avis', null],
        "\0".parent::class."\0".'conducteur' => [parent::class, 'conducteur', null],
        "\0".parent::class."\0".'date_depart' => [parent::class, 'date_depart', null],
        "\0".parent::class."\0".'heure_depart' => [parent::class, 'heure_depart', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lieu_arrivee' => [parent::class, 'lieu_arrivee', null],
        "\0".parent::class."\0".'lieu_depart' => [parent::class, 'lieu_depart', null],
        "\0".parent::class."\0".'nombre_places_disponibles' => [parent::class, 'nombre_places_disponibles', null],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null],
        "\0".parent::class."\0".'voiture' => [parent::class, 'voiture', null],
        'avis' => [parent::class, 'avis', null],
        'conducteur' => [parent::class, 'conducteur', null],
        'date_depart' => [parent::class, 'date_depart', null],
        'heure_depart' => [parent::class, 'heure_depart', null],
        'id' => [parent::class, 'id', null],
        'lieu_arrivee' => [parent::class, 'lieu_arrivee', null],
        'lieu_depart' => [parent::class, 'lieu_depart', null],
        'nombre_places_disponibles' => [parent::class, 'nombre_places_disponibles', null],
        'prix' => [parent::class, 'prix', null],
        'voiture' => [parent::class, 'voiture', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
