<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Voiture extends \App\Entity\Voiture implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'couleur' => [parent::class, 'couleur', null],
        "\0".parent::class."\0".'covoiturages' => [parent::class, 'covoiturages', null],
        "\0".parent::class."\0".'energie' => [parent::class, 'energie', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'immatriculation' => [parent::class, 'immatriculation', null],
        "\0".parent::class."\0".'marque' => [parent::class, 'marque', null],
        "\0".parent::class."\0".'modele' => [parent::class, 'modele', null],
        "\0".parent::class."\0".'nombre_places' => [parent::class, 'nombre_places', null],
        "\0".parent::class."\0".'premiere_immatriculation' => [parent::class, 'premiere_immatriculation', null],
        "\0".parent::class."\0".'utilisateur' => [parent::class, 'utilisateur', null],
        'couleur' => [parent::class, 'couleur', null],
        'covoiturages' => [parent::class, 'covoiturages', null],
        'energie' => [parent::class, 'energie', null],
        'id' => [parent::class, 'id', null],
        'immatriculation' => [parent::class, 'immatriculation', null],
        'marque' => [parent::class, 'marque', null],
        'modele' => [parent::class, 'modele', null],
        'nombre_places' => [parent::class, 'nombre_places', null],
        'premiere_immatriculation' => [parent::class, 'premiere_immatriculation', null],
        'utilisateur' => [parent::class, 'utilisateur', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
