# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
