security:
    # 🔹 Configuration du hashage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 🔹 Configuration des providers (chargement des utilisateurs depuis la base de données)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # 🔹 Configuration des firewalls (gestion des authentifications et accès)
    firewalls:
        # 🔹 Firewall pour la partie de développement
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # 🔹 Configuration principale pour l'authentification des utilisateurs
        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\LoginFormAuthenticator # 🔹 Ajout de l'entry_point
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /
            stateless: false  # 🔹 Devrait être "false" sauf si API totalement sans session
            custom_authenticators:
                - App\Security\LoginFormAuthenticator

    # 🔹 Contrôle d'accès pour différentes sections du site
    access_control:
        - { path: ^/espace-employe, roles: ROLE_EMPLOYE }
        - { path: ^/espace-administrateur, roles: ROLE_ADMIN }
        - { path: ^/api/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/avis, roles: IS_AUTHENTICATED_ANONYMOUSLY }

# 🔹 Paramètres spécifiques aux tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
