version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ecoride}
      MYSQL_USER: ${MYSQL_USER:-user}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql
  ###< doctrine/doctrine-bundle ###

volumes:
  database_data: