<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Avis extends \App\Entity\Avis implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'commentaire' => [parent::class, 'commentaire', null],
        "\0".parent::class."\0".'conducteur' => [parent::class, 'conducteur', null],
        "\0".parent::class."\0".'covoiturage' => [parent::class, 'covoiturage', null],
        "\0".parent::class."\0".'date_avis' => [parent::class, 'date_avis', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'note' => [parent::class, 'note', null],
        "\0".parent::class."\0".'passager' => [parent::class, 'passager', null],
        'commentaire' => [parent::class, 'commentaire', null],
        'conducteur' => [parent::class, 'conducteur', null],
        'covoiturage' => [parent::class, 'covoiturage', null],
        'date_avis' => [parent::class, 'date_avis', null],
        'id' => [parent::class, 'id', null],
        'note' => [parent::class, 'note', null],
        'passager' => [parent::class, 'passager', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
