<?php

namespace ContainerFIr4xzJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uPrBHkx.App\Controller\EmployeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uPrBHkx.App\\Controller\\EmployeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avisRepository' => ['privates', 'App\\Repository\\AvisRepository', 'getAvisRepositoryService', true],
            'covoiturageRepository' => ['privates', 'App\\Repository\\CovoiturageRepository', 'getCovoiturageRepositoryService', true],
        ], [
            'avisRepository' => 'App\\Repository\\AvisRepository',
            'covoiturageRepository' => 'App\\Repository\\CovoiturageRepository',
        ]))->withContext('App\\Controller\\EmployeController::index()', $container);
    }
}
