<?php

namespace ContainerFIr4xzJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoitureControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DEujfg9.App\Controller\VoitureController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DEujfg9.App\\Controller\\VoitureController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'voitureRepository' => ['privates', 'App\\Repository\\VoitureRepository', 'getVoitureRepositoryService', true],
        ], [
            'voitureRepository' => 'App\\Repository\\VoitureRepository',
        ]))->withContext('App\\Controller\\VoitureController::index()', $container);
    }
}
