<?php

namespace ContainerCxxRrxx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZvrVZ8sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZvrVZ8s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZvrVZ8s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::suspendreUtilisateur' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\AdminController::suspendreUtilisateur()', 'getAdminControllersuspendreUtilisateurService', true],
            'App\\Controller\\AdminController::activerUtilisateur' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\AdminController::activerUtilisateur()', 'getAdminControlleractiverUtilisateurService', true],
            'App\\Controller\\AuthentificationController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\AuthentificationController::login()', 'getAuthentificationControllerloginService', true],
            'App\\Controller\\EmployeController::validerAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::validerAvis()', 'getEmployeControllervaliderAvisService', true],
            'App\\Controller\\EmployeController::refuserAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::refuserAvis()', 'getEmployeControllerrefuserAvisService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:suspendreUtilisateur' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\AdminController::suspendreUtilisateur()', 'getAdminControllersuspendreUtilisateurService', true],
            'App\\Controller\\AdminController:activerUtilisateur' => ['privates', '.service_locator.EWAQaZu.App\\Controller\\AdminController::activerUtilisateur()', 'getAdminControlleractiverUtilisateurService', true],
            'App\\Controller\\AuthentificationController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\AuthentificationController::login()', 'getAuthentificationControllerloginService', true],
            'App\\Controller\\EmployeController:validerAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::validerAvis()', 'getEmployeControllervaliderAvisService', true],
            'App\\Controller\\EmployeController:refuserAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::refuserAvis()', 'getEmployeControllerrefuserAvisService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::suspendreUtilisateur' => '?',
            'App\\Controller\\AdminController::activerUtilisateur' => '?',
            'App\\Controller\\AuthentificationController::login' => '?',
            'App\\Controller\\EmployeController::validerAvis' => '?',
            'App\\Controller\\EmployeController::refuserAvis' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:suspendreUtilisateur' => '?',
            'App\\Controller\\AdminController:activerUtilisateur' => '?',
            'App\\Controller\\AuthentificationController:login' => '?',
            'App\\Controller\\EmployeController:validerAvis' => '?',
            'App\\Controller\\EmployeController:refuserAvis' => '?',
        ]);
    }
}
