<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOvkxPDt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOvkxPDt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOvkxPDt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOvkxPDt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOvkxPDt\App_KernelDevDebugContainer([
    'container.build_hash' => 'OvkxPDt',
    'container.build_id' => '92c64a85',
    'container.build_time' => 1739066274,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOvkxPDt');
