<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGjtUujQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGjtUujQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGjtUujQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGjtUujQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGjtUujQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'GjtUujQ',
    'container.build_id' => 'f4444f5a',
    'container.build_time' => 1739762944,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGjtUujQ');
