<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1YPQ5D9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1YPQ5D9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1YPQ5D9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1YPQ5D9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1YPQ5D9\App_KernelDevDebugContainer([
    'container.build_hash' => '1YPQ5D9',
    'container.build_id' => '4445d479',
    'container.build_time' => 1739231969,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1YPQ5D9');
