<?php

namespace ContainerMGssND1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SPPZzPiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sPPZzPi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sPPZzPi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\ApiRegistrationController::apiRegister' => ['privates', '.service_locator.2JsKP_J.App\\Controller\\ApiRegistrationController::apiRegister()', 'getApiRegistrationControllerapiRegisterService', true],
            'App\\Controller\\AuthentificationController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\AuthentificationController::login()', 'getAuthentificationControllerloginService', true],
            'App\\Controller\\CovoiturageController::index' => ['privates', '.service_locator.gcAlB65.App\\Controller\\CovoiturageController::index()', 'getCovoiturageControllerindexService', true],
            'App\\Controller\\EmployeController::index' => ['privates', '.service_locator.uPrBHkx.App\\Controller\\EmployeController::index()', 'getEmployeControllerindexService', true],
            'App\\Controller\\EmployeController::validerAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::validerAvis()', 'getEmployeControllervaliderAvisService', true],
            'App\\Controller\\EmployeController::refuserAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::refuserAvis()', 'getEmployeControllerrefuserAvisService', true],
            'App\\Controller\\ProfilController::index' => ['privates', '.service_locator.5FanY8e.App\\Controller\\ProfilController::index()', 'getProfilControllerindexService', true],
            'App\\Controller\\RechercheController::recherche' => ['privates', '.service_locator.MEs4xNG.App\\Controller\\RechercheController::recherche()', 'getRechercheControllerrechercheService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.BTkkvr3', 'get_ServiceLocator_BTkkvr3Service', true],
            'App\\Controller\\UserController::register' => ['privates', '.service_locator.IJqlBtP.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
            'App\\Controller\\VoitureController::index' => ['privates', '.service_locator.DEujfg9.App\\Controller\\VoitureController::index()', 'getVoitureControllerindexService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\ApiRegistrationController:apiRegister' => ['privates', '.service_locator.2JsKP_J.App\\Controller\\ApiRegistrationController::apiRegister()', 'getApiRegistrationControllerapiRegisterService', true],
            'App\\Controller\\AuthentificationController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\AuthentificationController::login()', 'getAuthentificationControllerloginService', true],
            'App\\Controller\\CovoiturageController:index' => ['privates', '.service_locator.gcAlB65.App\\Controller\\CovoiturageController::index()', 'getCovoiturageControllerindexService', true],
            'App\\Controller\\EmployeController:index' => ['privates', '.service_locator.uPrBHkx.App\\Controller\\EmployeController::index()', 'getEmployeControllerindexService', true],
            'App\\Controller\\EmployeController:validerAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::validerAvis()', 'getEmployeControllervaliderAvisService', true],
            'App\\Controller\\EmployeController:refuserAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::refuserAvis()', 'getEmployeControllerrefuserAvisService', true],
            'App\\Controller\\ProfilController:index' => ['privates', '.service_locator.5FanY8e.App\\Controller\\ProfilController::index()', 'getProfilControllerindexService', true],
            'App\\Controller\\RechercheController:recherche' => ['privates', '.service_locator.MEs4xNG.App\\Controller\\RechercheController::recherche()', 'getRechercheControllerrechercheService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.BTkkvr3', 'get_ServiceLocator_BTkkvr3Service', true],
            'App\\Controller\\UserController:register' => ['privates', '.service_locator.IJqlBtP.App\\Controller\\UserController::register()', 'getUserControllerregisterService', true],
            'App\\Controller\\VoitureController:index' => ['privates', '.service_locator.DEujfg9.App\\Controller\\VoitureController::index()', 'getVoitureControllerindexService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\ApiRegistrationController::apiRegister' => '?',
            'App\\Controller\\AuthentificationController::login' => '?',
            'App\\Controller\\CovoiturageController::index' => '?',
            'App\\Controller\\EmployeController::index' => '?',
            'App\\Controller\\EmployeController::validerAvis' => '?',
            'App\\Controller\\EmployeController::refuserAvis' => '?',
            'App\\Controller\\ProfilController::index' => '?',
            'App\\Controller\\RechercheController::recherche' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\UserController::register' => '?',
            'App\\Controller\\VoitureController::index' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\ApiRegistrationController:apiRegister' => '?',
            'App\\Controller\\AuthentificationController:login' => '?',
            'App\\Controller\\CovoiturageController:index' => '?',
            'App\\Controller\\EmployeController:index' => '?',
            'App\\Controller\\EmployeController:validerAvis' => '?',
            'App\\Controller\\EmployeController:refuserAvis' => '?',
            'App\\Controller\\ProfilController:index' => '?',
            'App\\Controller\\RechercheController:recherche' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\UserController:register' => '?',
            'App\\Controller\\VoitureController:index' => '?',
        ]);
    }
}
