<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPZraOjX\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPZraOjX/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerPZraOjX.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerPZraOjX\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerPZraOjX\App_KernelTestDebugContainer([
    'container.build_hash' => 'PZraOjX',
    'container.build_id' => '7d51b6dc',
    'container.build_time' => 1739762615,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPZraOjX');
