<?php

namespace ContainerGjtUujQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PzAAJKBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pzAAJKB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pzAAJKB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\AuthentificationController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\AuthentificationController::login()', 'getAuthentificationControllerloginService', true],
            'App\\Controller\\CovoiturageController::index' => ['privates', '.service_locator.gcAlB65.App\\Controller\\CovoiturageController::index()', 'getCovoiturageControllerindexService', true],
            'App\\Controller\\EmployeController::validerAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::validerAvis()', 'getEmployeControllervaliderAvisService', true],
            'App\\Controller\\EmployeController::refuserAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::refuserAvis()', 'getEmployeControllerrefuserAvisService', true],
            'App\\Controller\\RechercheController::recherche' => ['privates', '.service_locator.MEs4xNG.App\\Controller\\RechercheController::recherche()', 'getRechercheControllerrechercheService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.OzEre6h.App\\Controller\\AdminController::index()', 'getAdminControllerindexService', true],
            'App\\Controller\\AuthentificationController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\AuthentificationController::login()', 'getAuthentificationControllerloginService', true],
            'App\\Controller\\CovoiturageController:index' => ['privates', '.service_locator.gcAlB65.App\\Controller\\CovoiturageController::index()', 'getCovoiturageControllerindexService', true],
            'App\\Controller\\EmployeController:validerAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::validerAvis()', 'getEmployeControllervaliderAvisService', true],
            'App\\Controller\\EmployeController:refuserAvis' => ['privates', '.service_locator.i.fVVTo.App\\Controller\\EmployeController::refuserAvis()', 'getEmployeControllerrefuserAvisService', true],
            'App\\Controller\\RechercheController:recherche' => ['privates', '.service_locator.MEs4xNG.App\\Controller\\RechercheController::recherche()', 'getRechercheControllerrechercheService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AuthentificationController::login' => '?',
            'App\\Controller\\CovoiturageController::index' => '?',
            'App\\Controller\\EmployeController::validerAvis' => '?',
            'App\\Controller\\EmployeController::refuserAvis' => '?',
            'App\\Controller\\RechercheController::recherche' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AuthentificationController:login' => '?',
            'App\\Controller\\CovoiturageController:index' => '?',
            'App\\Controller\\EmployeController:validerAvis' => '?',
            'App\\Controller\\EmployeController:refuserAvis' => '?',
            'App\\Controller\\RechercheController:recherche' => '?',
        ]);
    }
}
